//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_AppNotification_POC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNotification
    {
        public string Id { get; set; }
        public string NotificationType { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationFrom { get; set; }
        public bool IsRead { get; set; }
        public string NotificationTo { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
        public virtual LoginDetail LoginDetail1 { get; set; }
    }
}
